### ISSUE TITLE
Rambox window "lost" when switching from 2 screen to 1 screen

### ISSUE THREAD

**Issue by RaydenX93** [TheGoddessInari/rambox#10]
### Steps to reproduce

1. Use a double monitor setup so you have 2 indipendent desktops, one primary and one secondary.
2. Put Rambox window on secondary desktop
3. Unplug secondary desktop

### Expected behavior

Rambox windows should automatically move on the primary desktop.

### Actual behavior

Rambox windows remains on secondary desktop. Needs to be manually moved to primary desktop with some tricks.

### ENVIRONMENT

> Rambox: v0.5.18-f96bbdd8

> OS: Windows 10

> Arch: x64

**Comment by TheGoddessInari** [comment]
I'm not sure this is fixable per https://github.com/atom/atom/issues/6939, https://github.com/electron/electron/issues/11349, etc. 

I can't reproduce this, either. Getting a 'removed monitor' event (rather than merely screen off) moves all windows on Windows 10 off of that screen, and Rambox will just recenter if loading out of bounds.

**Comment by RaydenX93** [comment]
I'm trying again and it seems like it's working now. Maybe there was something wrong with Windows. I'll close this for now. Thanks anyway.
