### ISSUE TITLE
Meta: Need appropriate artifact hosting for MacOS

### ISSUE THREAD

**Issue by TheGoddessInari** [TheGoddessInari/rambox#12]
Appveyor is taking care of the Windows and Linux builds, but currently all options that I can find for MacOS cost money or abuse the github tagging system quite severely and have issues with being a race condition (someone can be downloading a snapshot build that suddenly is being overwritten).

Options? Opinions?

**Comment by timbru31** [comment]
TravisCI seems to be able to upload artifacts to GitHub releases. With something like GitFlow you won't abuse the git tags too much IMHO.

**Comment by TheGoddessInari** [comment]
I previously tried using a nightly snapshot type tag to automatically load all of the build artifacts to, but github really doesn't support that well at all. 

For normal releases and tags it won't matter, but I feel bad for not having master build artifacts for MacOS.

**Comment by rodneyrod** [comment]
Is it possible to temp host it somewhere else for the time being?

**Comment by lawrencegripper** [comment]
I had a quick look at your travis file and it looks like the stuff is there for travis to upload the artifacts at the end of the build. I think you'll have already considered this but if you haven't then hopefully it's useful. 

If you use branches instead of tags then things get simple. You can have a Master and a Dev branch then have the dev branch build and publish pre-release releases to github and the master branch build and publish normal releases. For version numbers I've tended to use something like this

```
before_deploy:
- git tag "$(cat VERSION)-$(git log --format=%h -1)"
```

When the release task runs in travis it will pick up that tag and set it as the tag on the release. This means you don't need to do the `git push` to publish the tag back to the repo.... the travis release task will do that for you. 
Then you switch development work to the dev branch and when at a point which is stable for a feature release merge that into the master.

**Comment by vraravam** [comment]
One quick suggestion: you can use [yaml anchor](http://yaml.org/spec/current.html) nodes syntax to remove duplication of the `deploy` node in the example above.

**Comment by vraravam** [comment]
@TheGoddessInari - I would like to become a beta tester for this package. I use a Mac (currently on OS Mojave), and can even help out with homebrew-based installations testing, etc...but, am still waiting for where the download links point to.

**Comment by TheGoddessInari** [comment]
This is more or less closed by the fact that Azure DevOps is in use now.
