### ISSUE TITLE
"Check for updates" for unstable builds and auto-updater features

### ISSUE THREAD

**Issue by RaydenX93** [TheGoddessInari/rambox#13]
The "Check for updates" feature is currently not showing newer versions. This is probably intended since no stable releases have been released yet but probably it could be useful to give the user the ability to opt-in for newer unstable builds directly from the program, maybe after dealing with #9 .

Also, could an auto-updater be implemented, so that the update is seamless to the user?

Thank you.

**Comment by TheGoddessInari** [comment]
Yes, eventually. It's still checking upstream for updates. I should probably comment it out for now,
Unstable builds are very much linked with #9.
Once #9 is closer to being realized, the same machinery would allow injecting the appveyor build number which increases monotonically, and would allow comparing a running build from there with the master build.
I believe the Windows squirrel updater would work with that.

I want to get this and several functional updates for 0.5.18.

**Comment by TheGoddessInari** [comment]
Closing this for now because #9 and #22 more directly address the remaining problems since #16 determined that auto-update isn't really necessary, at least if we can link to the appropriate release or build artifact.

We can revisit auto-update in the future, but right now, only Windows supported auto-updating upstream or with electron, and in particular replacing the asar or paks while in use can be error prone as far as researching electron goes. Auto-updating will probably remain curbed until electron-builder gets multi-platform auto-updating, or an appropriate multi-stage multi-platform third party solution can be integrated properly.
