### ISSUE TITLE
Login button does nothing + local backup?

### ISSUE THREAD

**Issue by RaydenX93** [TheGoddessInari/rambox#21]
### Steps to reproduce

1. Click the "Login" button in the main Rambox window.

### Expected behavior

Not really sure what should happen. But something should happen if you click a button, right?

### Actual behavior

Nothing happens.

### ENVIRONMENT

> Rambox: v0.5.18-dced932

> OS: Win 10

> Arch: x64

BTW, as far as I know, that "login" button should need to backup the Rambox settings online. Can we also find a way to have a local backup in a file so I can put it wherever I like?

Thanks.

**Comment by TheGoddessInari** [comment]
I was starting to update this, but it's saenzramiro/rambox#1698.
Upstream isn't updating their panel, so the two options above stand.
Stashing and putting this back to todo.

**Comment by RaydenX93** [comment]
Correct me if I'm wrong but I have the impression that your first priority is to fix Rambox instead of adding new features to it and I totally agree with that. 

Therefore, I believe for now it's enough to remove Auth0, which is broken. When the most urgent problems will be solved, we could think of implementing a simple system that allows to backup/restore your options and the services you're connected to, all with their own settings (mute sounds, hide notifications, etc.). 

The service sessions do not need to be carried over, that is, it's ok if I have to login again to each service but at least I don't have to go through the hassle of setting up all my services again from the Rambox list, etc.

**Comment by TheGoddessInari** [comment]
It's pretty reasonable to expect to be able to do some form of (human readable) backup, especially one that could easily be saved to portable drives or cloud storage, and work reasonably between versions.
The local_storage for session persistence and preferences also aren't guaranteed to work well between versions.
I'd consider that a pretty serious issue, even if it doesn't affect day to day usability.
However, it's the one thing that's really "set in stone". If you do it wrong while trying to clean it up and fix it, it can cause even more problems down the line.

Bluntly, I'd rather get the wisdom of someone more experienced in Javascript/JSON and tackling such versioning issues, as I know enough to know there's a giant nest of caveats and it's extremely difficult to get right unless you can get the help from experienced implementors. That said, I'll still look to see if there's a stable library or well-documented procedure out there for this.

It does make sense to rip out Auth0 before 0.5.18, but if I go that way, I'd rather not have to simply add it back in after a week if something gets fixed.

**Comment by TheGoddessInari** [comment]
Upstream [jumped the shark](https://github.com/saenzramiro/rambox/issues/1810) and went closed source. I'll do my best to look into replacement for Auth0 **today**. I'll also check in with Auth0, just in case they'd want to give us our own panel.

**Comment by TheGoddessInari** [comment]
I'll probably rip out Auth0 due to GDPR unless someone can explain to me why that wouldn't be necessary.
According to Auth0 and a reading of the GDPR, as far as I can tell, the situation is the following:
- Open Source needs to comply.
- Open Source is not really given tools to comply in an easy manner.
- Using Auth0, or total automation, or not actually handling ANY data or secrets myself, wouldn't preclude this project from needing to comply with all terms, including a dedicated GDPR/security compliance officer.
- The only way to get around this is by allowing backup/restore to a user's own services, such as allowing local file storage, enough integration to allow easier backup/restore with various cloud drives.
- If a user provides their very-own storage backing, the project isn't liable if anything happens to the data.
- Do we need to have data security on the localstorage blobs? Is that even really feasible with an ancient version of ExtJS?

**Comment by TheGoddessInari** [comment]
I should have a version on testing "soon" that can do backup/restore from JSON files. It doesn't have any special handlers for cloud stuff, as I'm not sure the NodeJS ecosystem supports that very well.

It also has removed Auth0, since it's not useful anymore, had never worked if you had any disabled services, and I'm unlikely to be able to handle GDPR compliance.

File backup should work with any paths that your environment's native file picker (as decided on by electron), including ones introduced by any extensions or loaders there, such as OneDrive on Windows, and it is human-readable JSON, since it only saves approximately 5% of filesize to have the default minified output.

**Comment by TheGoddessInari** [comment]
I'd suggest not testing those functions on your main profile. You can make copies and use one of those instead.

**Comment by TheGoddessInari** [comment]
Closing this because there's now backup/restore, and the issues left also happen upstream.

Presumably someone besides me tested it.
