### ISSUE TITLE
Start Rambox-OS if Rambox-OS is running

### ISSUE THREAD

**Issue by LiBOSS-CZ** [TheGoddessInari/rambox#41]
I have double clicked on Rambox-OS icon, but Rambox-OS has already been running and I have recieved uncaught exception.

### Steps to reproduce
1. Start Rambox-OS
2. Start another Rambox-OS

### Expected behavior
There are two possibilities. Focus on actually running window or run another instance.

### Actual behavior
Uncaught exception.

![rambox-os_error](https://user-images.githubusercontent.com/41294900/44642229-80d99b00-a9cb-11e8-8625-2e13149aed21.png)

### ENVIRONMENT
> Rambox-OS: v0.5.18 build 150 (latest master)
> OS: Windows 10 Pro
> Arch: x64

**Comment by TheGoddessInari** [comment]
Apparently this is due to the removed 'return' (which is still technically illegal in javascript when in global scope), since app.quit asks very nicely, is asynchronous, and there's no way to specify a timeout, and electron documentation doesn't reflect this (of course).

Since we don't actually DO anything on quit that'd require the hooks, going to just change calls to quit into calls to exit, as this also solves a problem I noticed with quit potentially hanging, at least on Windows 10.

**Comment by TheGoddessInari** [comment]
Forgot to put it in the commit log, but da64582cf3c0026a1b06b3a936f813d9b629a220 closes this.
