### ISSUE TITLE
Unable to connect to ICQ

### ISSUE THREAD

**Issue by LiBOSS-CZ** [TheGoddessInari/rambox#45]
Install new artifact 0.5.18-158. Unable to load ICQ. Remove ICQ services and try to add new one but unable to confirm a log in. Till 0.5.18-155 it has been working. Since 0.5.18-156 it does not work anymore.

### Steps to reproduce
1. Add new ICQ services
2. Login by number
3. unable to confirm by enter

### Expected behavior
Log in ICQ account

### Actual behavior
Nothing happened if I click on enter or push the enter button.

### ENVIRONMENT
> Rambox-OS: v0.5.18-158
> OS: Windows 10
> Arch: x64

**Comment by TheGoddessInari** [comment]
Will be fixed with 2f6e6ffa98f66b8fefca02c3bfe615b4ed85ef5d. web.icq.com uses eval(), including in its login process. Inside the app, exceptions appear to be caught and trapped silently, and partially works anyway, which is why I didn't discover it before pushing.

They also don't have a standard security email address. 🥇

**Comment by TheGoddessInari** [comment]
Should be fixed, comment if it isn't.
