### ISSUE TITLE
copy&paste problems when using slack

### ISSUE THREAD

**Issue by danielmotaleite** [TheGoddessInari/rambox#58]
Can you please take a look to 

https://github.com/ramboxapp/community-edition/issues/1235

I just tested your version and it also have the same problem.
Notice my last few comments, where i asked slack how they fixed this problem on their app... no idea how to do that, but maybe you do understand it

**Comment by TheGoddessInari** [comment]
Unfortunately, Slack can use BrowserView because they can trust all of the remote content loaded since its theirs. In electron/electron#10323 it's documented that only a single BrowserView is supported per BrowserWindow.

Security already can't necessarily be stricter because of electron limitations surrounding sandbox, contextIsolation, and others, not counting their experimental status. This is a lot better on security than upstream, but it's a matter of degrees.

Since everything else is going to have to get ripped out at some point (why am I not just reimplementing this in C++?), do other similar engines (like nw.js) have these problems with webview or the equivalent, if there's some way you could find out?

**Comment by danielmotaleite** [comment]
i never had any copy&paste problems until one slack update... it was the final push for me to move to rambox... but a few weeks later rambox also had a update and it also had the copy&paste problem.
When later slack released a new version, the copy&paste problem was solved, but rambox never manage to solve it. So as test other engines... i can't directly test this, but this copy&paste problem seem related with electron and something that slack uses... it this will also affect other engines, its unknown :)

**Comment by TheGoddessInari** [comment]
Closing this because reporter never got back to me and it sounds like it's Slack abusing things.
