### ISSUE TITLE
Zoho Email not retaining login

### ISSUE THREAD

**Issue by ontherunvaro** [TheGoddessInari/rambox#64]
See https://github.com/ramboxapp/community-edition/issues/1599

Basically, login state is lost after the app is closed for Zoho Email, regardless of choosing "keep me signed in" during login. This is not an issue with the Zoho webpage, as it works as expected in a browser, and users on the issue linked above report it on more services.

**Comment by TheGoddessInari** [comment]
Can you check if this still happens on master, with electron 3.0.8? I can't reproduce the behavior with the associated improvements on session saving, either with reload or quit/restart.

It's looking like the issue with non-menu shortcuts in #66 may be the lesser of evils.

In your linked comment, people mention getting logged out of Slack 100% of the time, which I haven't seen. Some small percentage of the time due to system crashes, but not in general on this fork.

It's worth noting that the behavior of Chrome (also mentioned in your linked comment) is abnormal in this regard, as it persists all session cookies and session storage unless you explicitly clear it. This intentionally violates web standards to be more convenient with broken webapps at the cost of privacy (and possibly security as well). This **isn't** what's affecting Zoho Email, but some other things, such as WhatsApp previously. If it works in Firefox, it **should** work in this project.

In a related note, Electron doesn't make available Chrome's "enhanced" session storage capability, and the main workaround on our end would be to try and wrap session storage and session cookies and persist them in localStorage, which I'm certain would have extremely negative implications. If anyone has a better idea, I'm certainly listening.

**Comment by ontherunvaro** [comment]
Can confirm it happens on a fresh built version from `master`, both on reload and on quick-restart.

**Comment by TheGoddessInari** [comment]
I'm not sure what to make of this. I've tested on both Windows and Linux, and Zoho Email stays logged in.

Any more information you could narrow down about the problem would be helpful.

If it's not retaining login at this point, it could be there's a problem with storage that's only affecting OSX.

**Comment by ontherunvaro** [comment]
That's strange, I actually am using Linux myself (Tested on Ubuntu 18.04 and 16.04).

There's a variable I hadn't considered yet: is your account a `zoho.com` email or a `zoho.eu` one?
Mine is a `zoho.eu` account, and I see the service uses mail.zoho.com as an entrypoint.

In a browser, if I login through mail.zoho.com, I am redirected (and logged in) to mail.zoho.eu. Maybe this is causing problems with the storage?

**Comment by ontherunvaro** [comment]
> In a browser, if I login through mail.zoho.com, I am redirected (and logged in) to mail.zoho.eu. Maybe this is causing problems with the storage?

This is indeed the problem. As a means to test it [i've added a clone service](https://github.com/ontherunvaro/rambox/commit/ceaa1db1583ff52218cc89a753a2650c48c078d9) changing only the URL and name. 

As suspected, after a reload the Zoho EU tab retains login state, while the default zoho.com does not.

**Comment by TheGoddessInari** [comment]
I don't think it'd be a good idea or precedent to split Zoho into US and EU specific versions (bad Zoho, bad).
I could make the .com portion a blank, but that might confuse some people.

**Comment by vraravam** [comment]
Same is the case for `zoho.in` domain.

**Comment by TheGoddessInari** [comment]
The gist is, Travis CI doesn't have integration for 'regular' file storage providers, and most options, such as GCP or S3, would involve me paying out of pocket for file storage which isn't feasible.

The only reason there are Linux builds is because AppVeyor supports it nowadays. As far as [this support ticket](https://help.appveyor.com/discussions/questions/21362-os-x-support) goes, AppVeyor claims that Mac builds will come before the end of the calendar year.

**Comment by ontherunvaro** [comment]
@TheGoddessInari The `testing` version works fine.

I can't think of a more appropriate workaround, since duplicates are out of question, especially if as @vraravam says there are even more incompatible domains.

**Comment by TheGoddessInari** [comment]
If not obvious, testing version was pushed to `master`. People with existing Zoho stuff will need to add in the appropriate TLD. I wish Zoho had designed this better. I checked all kinds of ways and I'm not seeing a reasonable way to add a default with the current restrictions, with respect to Sencha design problems.
