### ISSUE TITLE
README: DMG download link for macOS missing

### ISSUE THREAD

**Issue by chnbz** [TheGoddessInari/rambox#65]
In the Readme there are links to download releases for Windows and Linux, but not for macOS.

**Comment by ontherunvaro** [comment]
See #12 for details

**Comment by vraravam** [comment]
@TheGoddessInari - any updates on this?

**Comment by TheGoddessInari** [comment]
There isn't really a place to hold versioned artifacts for free, even for open source, that I'm aware unless you're also building on the platform (ala AppVeyor).

I had tried github tags, but hadn't been able to work out the exact sequence needed for it to work as intended (certain branches get current artifacts built and pushed, but with atomic link updates, otherwise the files can disappear or glitch during a build.)

**Comment by vraravam** [comment]
What about `megaupload` or any of the other services that are listed here? https://www.raymond.cc/blog/100mb-free-file-hosting-with-expiring-links/ - maybe that can be used while beta testing and to show progress?

**Comment by vraravam** [comment]
For the branches, I would suggest that file uploads/hosting (for beta testing) is only done for the master branch. Most likely, code in branches will have to be reviewed by a committer (human person) - who has the ability create the distributable locally for testing. In such case, why does it need to hamper the contribution (by ppl like me who can help in testing - and not necessarily javascript coding)

**Comment by TheGoddessInari** [comment]
The gist is, Travis CI doesn't have integration for 'regular' file storage providers, and most options, such as GCP or S3, would involve me paying out of pocket for file storage which isn't feasible.

The only reason there are Linux builds is because AppVeyor supports it nowadays. As far as this support ticket goes, AppVeyor claims that Mac builds will come before the end of the calendar year.

**Comment by vurtomatic** [comment]
Hi, I'm curious to check this out and was wondering if a Mac DMG can be hosted on a free file sharer too.

**Comment by TheGoddessInari** [comment]
Not really as you need unlimited or "rolling" storage because the builds take up considerable space, then you have to keep old versions around for a while. For a free-time open source project, nearly everything would be paid. Things other than AppVeyor also tend not to support atomic link updating, so you can start downloading something, but the binary you're downloading starts getting overwritten by a new release mid-download. Not good.

The gist is, AppVeyor just needs to support MacOS so it can all be unified.
Else, if you know of a free CI host that works similarly to AppVeyor with build hosting, even if it doesn't support all three, I can use that in the mean time.

**Comment by rodneyrod** [comment]
What about manually rolling a DMG and hosting it somewhere like Mega?
It wouldn't be 'live', but I'd rather take slightly outdated builds over no builds at all.

**Comment by vurtomatic** [comment]
> What about manually rolling a DMG and hosting it somewhere like Mega?
> It wouldn't be 'live', but I'd rather take slightly outdated builds over no builds at all.

Yes that's what I was hoping for! Doesn't need to be "cutting edge", better than nothing.

> I'll try to see if I can figure something out with bintray by the weekend.

Thank you very much for looking into this!

**Comment by vraravam** [comment]
I came across a post - and found out that azure pipeline supports build agents that use mac OS. Would that be an option to figure out a way to build the DMGs for this?

**Comment by TheGoddessInari** [comment]
It's come to my attention that the new owners are gutting TravisCI, have fired almost everybody.
I put in a request to AppVeyor that they get back to me about the MacOS support timeline, but they're ignoring that as much as they are twitter.
I had looked into Microsoft CD/CI offerings before, but there was nothing that really worked in a reasonable manner. AppVeyor provides free automatic rolling storage for 6 months which is pretty critical if you can't afford separate hosting infrastructure for non-releases.
I'll take a close look at Azure Pipelines and whatever else is on offer currently. 
I'm sorry I haven't had a huge amount of time to work on things lately, but on the bright side things are pretty stable.

**Comment by vurtomatic** [comment]
We appreciate the update and thank you for keeping at it!

**Comment by TheGoddessInari** [comment]
Maybe I'm misunderstanding Azure DevOps, but I can't figure out a way for it to hold artifacts in a user-friendly way, or take 'latest successful' build results and produce a nightly rerelease that always has the same URL to download.

That said, this should be latest app/DMG for MacOS from `master`. https://dev.azure.com/TheGoddessInari/rambox/_build/results?buildId=27&view=results

**Comment by TheGoddessInari** [comment]
This should work. If it doesn't, perhaps someone can better enlighten me on how to get around some of the Azure DevOps quirks.

**Comment by vurtomatic** [comment]
Downloaded and got it running. Thank you so much for this!!

**Comment by TheGoddessInari** [comment]
Hm. @vurtomatic It's actually working? I'm running into problems because of the newer Sencha CMD (of course they'd break existing stuff...)

**Comment by vurtomatic** [comment]
This is really odd. I use Rambox for Whatsapp and Facebook Messenger. Rambox-OS worked initially but when I just ran the app again, Whatsapp is now telling me to update Google Chrome.

**Comment by TheGoddessInari** [comment]
If you're updating from a really old build, you may need to clear WhatsApp's storage and relink it.

**Comment by vraravam** [comment]
I had to delete the old preferences/registered services with this:
```find Library -iname "*rambox*" -exec rm -rfv {} \;```
and then it started working. Still setting up various services to be able to check features.

**Comment by vurtomatic** [comment]
> If you're updating from a really old build, you may need to clear WhatsApp's storage and relink it to your phone.
> 
> Else WhatsApp is trying to screw with electron users again, but I can't see that in my testing.

That worked. I removed and re-added WhatsApp. Rambox-OS is working great from what I can tell, thank you again!

**Comment by vraravam** [comment]
@TheGoddessInari - none of the keyboard shortcuts seem to work in this build on Mac OS Mojave. Should I create a new bug for this? (Even `Cmd+Q` for quitting the app doesn't work atm.

**Comment by TheGoddessInari** [comment]
@vraravam Yeah, open a bug. It should be (and show in the menu as) cmd+shift+q now.

If you were using really old builds, we've been through several Electron updates, and they don't allow the old way of hooking stuff up, and it doesn't seem very feasible for me to figure out how to make my own special input handler, as VSCode does.

Shortcuts changing and a ctrl-1 through ctrl-9 being dropped are related to #66.
If there's anything that **should** be working, please do make an issue for it.

Likewise, if anyone can figure out a more reliable way to handle the shortcuts in Electron 3 or 4, I'm happy to do something about it,

**Comment by vurtomatic** [comment]
>  It should be (and show in the menu as) cmd+shift+q now.

Not cmd+q?

**Comment by TheGoddessInari** [comment]
I know most Mac apps use cmd+q or similar, but from my days of hackintoshing, I remember some using cmd+shift+q as well. Since there isn't really a confirmation on exit, seems like a decent thing to default to a key combo that you shouldn't be able to hit accidentally. On Windows, that ended up ctrl+q which is easy to hit accidentally instead of ctrl+a.

**Comment by vurtomatic** [comment]
I see. If all Mac apps use cmd + q though, would it be better for a consistent experience? I think my fingers (or most Mac users) already have the muscle memory ingrained. Anyway Mac OS has the ability to customize keyboard shortcuts—I just succeeded in manually adding cmd+q to quit Rambox-OS.

![screenshot 2019-03-03 18 47 32](https://user-images.githubusercontent.com/7212035/53707688-d791b880-3de4-11e9-9b7d-f5d1246b1f6b.png)

**Comment by chnbz** [comment]
All apps on mac use cmd + q. I don't know any app that uses cmd+shift+q.

**Comment by TheGoddessInari** [comment]
@chnbz @vurtomatic @vraravam Would cmd+q giving a dialog box asking if you're sure you want to quit be sufficient? Or something else not idiomatic to MacOS?

**Comment by vurtomatic** [comment]
Typically cmd+q closes an app without a dialog box unless an operation in progress would be interrupted, such as a file transfer or an unsaved document.

**Comment by TheGoddessInari** [comment]
I misread on this, cmd+q added in d0a0aff.
