### ISSUE TITLE
Question: Original Rambox vs Fork?

### ISSUE THREAD

**Issue by MaskyS** [TheGoddessInari/rambox#67]
I see that the original rambox is actively maintained as well; What's makes this fork different?

**Comment by TheGoddessInari** [comment]
More of a focus on security where feasible. More actual attention paid to issues. 

The original Rambox, as repeatedly pointed out in bugs like https://github.com/ramboxapp/community-edition/issues/1954, isn't being properly maintained and is mostly seeing a lot of churn for churn's sake, and they've started mass-closing and locking issues via bot to make it seem like there are fewer problems with the software than there are.

I tried to make everything available to upstream, but they make things very difficult to work with and have showed zero interest in collaboration or getting to the bottom of serious bugs, so I'm trying to figure out the hellscape that is Electron-based app development. :P

While I haven't been as active as I'd like, I'm happy to accept and encourage contributions while I slowly work through the backlog. I've no plans to change for anything, let alone for 'basic' stuff like spellcheck, which the original is indeed happily charging money for. Nor will I be trying to sneak any tracking in, which was a problem with the original too.

Electron 3.0.8 is currently being used on master, which is a lot more stable; it has a problem with non-menu shortcuts because it uses Out of Process for the webviews, but trying to figure out how to work around that currently.

This fork'll probably be renamed Hamsket in the near future and get a new logo/icon. I wanted to do so sooner, but was also hoping for some help with some of the smaller issues for the next version which is required before that happens, so in theory you could migrate from Rambox 0.5.17 using intermediate builds.

As far as features, there's also a slower timer granularity, and passive input listeners for vastly reduced CPU usage. It'll get more over time, mostly been focusing on stability and security because the software's desperately needed it.

**Comment by MaskyS** [comment]
Appreciate the in-depth explanation; I did not check the closed issues tab of the rambox project and assumed proper maintenance by the looks of the low open issues ratio and commit dates. Now that I actually looked into it, seems pretty bad. Thanks for your work, will give your fork a try! 😄

**Comment by e-stonia** [comment]
How would you compare it to the original now in 2019? I see there are still active commits a few days ago. Good job!

**Comment by TheGoddessInari** [comment]
Oh, thanks for the question @e-stonia. Well, a lot's happened and a **lot** of progress has been made over the last year.

Obviously, my fork is still active and being resourcefully maintained. While for me, it's largely been a one-person effort, it's still software I use and care about each and every day. I've put countless hours into ensuring that security, privacy, performance, and usability are updated in a timely manner, and that each code change is efficient and "dogfooded" (tested by myself) before anything hits `master`, then the `nightly tag`, then eventually gets rolled into a release.

`Rambox-OS` (the older 0.5, Electron 5.x branch) is more stable, at the present time, as each commit is tested on nightly, and only merged after receiving more extended testing. But `Hamsket`, the new, rebranded fork is receiving a lot of attention and electron updates (now on 7.0.0!), and will be releasing a new stable version fairly soon (I hope!).

Hamsket was able to get some funding through some rainy days, but now that I'm working full-time with steady hours, I'll actually have **more** time to devote to the software, overall, while not having to depend on it financially. That said, I'll soon offer Github Sponsorship, where people will be able to safely, securely donate monthly, and know that, should I stay gainfully employed, ~99% of the donated money will go directly back into Hamsket, offering new features, infrastructure for the project itself, more timely performance, security updates, and possibly being able to attract some new developers to the project with greater expertise than I personally possess (especially in the UI and art) department.

I'll be able to soon replace the existing logos and artwork, so we'll be fully free and unemcumbered by the upstream fork (Rambox CE), as well as be able to offer a much better user-experience (UX) to each and everyone who downloads the software.

I'm also looking forward to Sencha releasing a new GPL version of ExtJS (7.1) that will enable bringing the interface and dependent framework up to 21st century ideals of security, performance, and usability.

So things are looking **really** bright for Hamsket, while unfortunately for the upstream repository, Rambox CE seems mostly concerned about updating donation links while otherwise letting the software rot in favor of their closed-source, proprietary "pro" version.

I'm hard at work on brand new features also offered by "Pro", including spell-check, adblocking,, and other heavier, more difficult to implement features, thanks to work by the larger javascript community.

I'm also spending some time improving the ecosystem offered by the Rust programming languages to projects similar in size, scope, and web-dependence to my beloved Hamsket project. So eventually, I hope to bring a secure, native, performant rewrite to Hamsket utilizing Rust and the much-improved, very secure `Servo` web-engine instead of depending on Electron's whims and variability on security issues.

All said, things are looking **great** for Hamsket, and I hope to be able to offer this software, and these improved features very soon, and for as long as I'm around. Again, it's software I use and enjoy and benefit from **every day**, and I hope to be able to help, gather, create, and encourage a larger community around the software that gets to benefit every day from such lovingly crafted software written by a developer who is committed to transparency, honesty, and their secure and private use of free, open source, and community-based software for decades to come. :) 🦊
