### ISSUE TITLE
Focus doesn't follow current tab when using keyboard shortcuts

### ISSUE THREAD

**Issue by mcarlton00** [TheGoddessInari/rambox#95]
### Steps to reproduce

1. Send a message using ServiceA
2. Use keyboard shortcuts to go to ServiceB (control+tab or Alt+left/right)
3. Start typing a new message

### Expected behavior
Focus to follow the current tab and be able to start typing in ServiceB immediately.

### Actual behavior

Focus stays on ServiceA and key commands will go there instead of the current tab.  This can result in sending messages to the wrong service/person if you're not paying attention to your cursor.

### ENVIRONMENT

Version: 0.5.18
Platform: linux (x64)
Electron: 4.0.8
Chromium: 69.0.3497.128
Node: 10.11.0
BuildVersion: 798ee1e (grafted, HEAD, tag: nightly, origin/master) Tue, 12 Mar 2019 12:45:11 -0700

Note: Installed using `rambox-os-bin` from the Aur

> Does this happen upstream: yes, no, unknown, or N/A

unknown

**Comment by TheGoddessInari** [comment]
As mentioned in documented in #66, this was known to be the case, except I didn't know the focus was staying on the previous page. That's a vital clue.
Turns out, it's another Electron regression, ala electron/electron#15718.
Unfortunately, the blur workaround mentioned doesn't seem to be effective, so I'll have to investigate further.
