### ISSUE TITLE
Slack doesn't work in nightly

### ISSUE THREAD

**Issue by burgerga** [TheGoddessInari/rambox#96]
I get a blank screen in my Slack window

```
VM118:1 Uncaught ReferenceError: $ is not defined
    at checkUnread (<anonymous>:1:38)
checkUnread                   @ VM118:1
setInterval (async)
(anonymous)                   @ VM118:1
WebFrame.(anonymous function) @ /opt/Rambox-OS/resources/electron.asar/renderer/api/web-frame.js:56
resolve                       @ /opt/Rambox-OS/resources/electron.asar/renderer/web-frame-init.js:15
ipcRenderer.on                @ /opt/Rambox-OS/resources/electron.asar/renderer/web-frame-init.js:14
emit                          @ events.js:182
``` 

in the Developer tools. Removing/re-adding/reloading doesn't make a difference. Works fine on a previous version on a different computer.

I'm running on Ubuntu 18.04 using a deb from the Github readme:

```
Version: 0.5.18
Platform: linux (x64)
Electron: 4.1.1
Chromium: 69.0.3497.128
Node: 10.11.0
BuildVersion: 4f95cfc (grafted, HEAD, tag: nightly, origin/master) Tue, 26 Mar 2019 09:41:31 -0700
```

**Comment by TheGoddessInari** [comment]
Looks like for some reason your Slack isn't loading jQuery. That shouldn't be possible, but I'll change the unread checker anyway.

**Comment by burgerga** [comment]
Thanks, the message in de Developer Tools is gone, but Slack doesn't load at all, so likely it's another issue :(

**Comment by TheGoddessInari** [comment]
Could network requests be getting blocked? Software firewall suddenly taking offense? May want to try to inspect elements/view source code.

I'm not sure what could be causing it otherwise. There's a build before Electron 4.1.1 over here. https://dev.azure.com/TheGoddessInari/rambox/_build/results?buildId=55

Artifacts button at the top right, could download any of the individual linux artifacts. Could try that, but I'd be really surprised if it stopped working from electron updates. Some people have reported very strange linux issues though, which are very hard for me to test in full.

**Comment by burgerga** [comment]
Sorry, I'm an idiot :disappointed: 
The network console showed me that `https://https://<myworkspace>.slack.com.slack.com` wouldn't load, that's what you get for copy pasting the slack url into the settings :(
Once I just entered the workspace name everything was fine.
